name: "Update pre-commit config"
# You need to set an access token as a secret ACTION_TRIGGER_TOKEN on this repo
# in order for the PR to trigger the CI.
# For more details see: https://github.com/technote-space/create-pr-action#github_token
# If you don't want the PR to trigger the CI (NOT RECOMMENDED), comment out the GITHUB_TOKEN line.

on:
  workflow_dispatch:

jobs:
  update-pre-commit:
    if: github.repository_owner == 'glotaran'
    name: Autoupdate pre-commit config
    runs-on: ubuntu-latest
    steps:
      - name: Set up Python
        uses: actions/setup-python@v4
      - uses: actions/cache@v3
        with:
          path: ~/.cache/pre-commit
          key: pre-commit-autoupdate
      - name: Update pre-commit config packages
        uses: technote-space/create-pr-action@v2
        with:
          GITHUB_TOKEN: ${{ secrets.ACTION_TRIGGER_TOKEN }}
          EXECUTE_COMMANDS: |
            pip install pre-commit
            pre-commit autoupdate || (exit 0);
            pre-commit run -a || (exit 0);
          COMMIT_EMAIL: 41898282+github-actions[bot]@users.noreply.github.com
          COMMIT_MESSAGE: "⬆️ UPGRADE: Autoupdate pre-commit config"
          PR_BRANCH_NAME: "pre-commit-config-update-${PR_ID}"
          PR_TITLE: "⬆️ UPGRADE: Autoupdate pre-commit config"
