name: "Trigger-Binder-build"
on:
  push:
    branches:
      - main
  workflow_dispatch:

jobs:
  trigger-binder-build:
    runs-on: ubuntu-latest
    steps:
      - uses: s-weigand/trigger-mybinder-build@v1
        with:
          target-repo: glotaran/pyglotaran
          target-state: main
